# Generated by Django 3.2 on 2021-05-08 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_type', models.TextField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BaseIgog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.PositiveBigIntegerField()),
                ('payment_type', models.TextField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('giro', 'Giro')], default='cash')),
                ('payment_status', models.TextField(choices=[('not_started', 'Not Yet Started'), ('installment', 'Installment'), ('finished', 'Finished')], default='not_started')),
                ('due_date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('baseigog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igog.baseigog')),
            ],
            bases=('igog.baseigog',),
        ),
        migrations.CreateModel(
            name='IncomingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField()),
                ('price_per_count', models.PositiveBigIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('incoming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igog.incoming')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingDeliveryNote',
            fields=[
                ('basedeliverynote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igog.basedeliverynote')),
                ('incoming_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            bases=('igog.basedeliverynote',),
        ),
        migrations.AddField(
            model_name='incoming',
            name='products',
            field=models.ManyToManyField(through='igog.IncomingProduct', to='products.Product'),
        ),
    ]
