# Generated by Django 3.2 on 2021-05-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdeliverynote',
            name='incoming_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igog.incoming'),
        ),
    ]
