# Generated by Django 3.2 on 2021-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseigog',
            name='price_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
