# Generated by Django 3.2 on 2021-06-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseigog',
            name='total_price',
        ),
    ]
