# Generated by Django 3.2 on 2021-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0002_baseigog_price_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseigog',
            name='installment_month',
        ),
        migrations.AddField(
            model_name='baseigog',
            name='installment_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseigog',
            name='installment_tenor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
