# Generated by Django 3.2 on 2021-05-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0002_alter_incomingdeliverynote_incoming_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdeliverynote',
            name='basedeliverynote_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='igog.basedeliverynote'),
        ),
        migrations.AlterField(
            model_name='incomingdeliverynote',
            name='incoming_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='igog.incoming'),
        ),
    ]
