# Generated by Django 3.2 on 2021-07-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0003_auto_20210702_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproduct',
            name='incoming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igog.incoming'),
        ),
        migrations.AlterField(
            model_name='outgoingproduct',
            name='outgoing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igog.outgoing'),
        ),
    ]
