# Generated by Django 3.2 on 2021-05-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210509_0026'),
        ('igog', '0003_auto_20210508_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('baseigog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igog.baseigog')),
            ],
            bases=('igog.baseigog',),
        ),
        migrations.CreateModel(
            name='OutgoingDeliveryNote',
            fields=[
                ('basedeliverynote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='igog.basedeliverynote')),
                ('outgoing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='igog.outgoing')),
            ],
            bases=('igog.basedeliverynote',),
        ),
        migrations.CreateModel(
            name='OutgoingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField()),
                ('price_per_count', models.PositiveBigIntegerField()),
                ('outgoing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igog.outgoing')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='outgoing',
            name='products',
            field=models.ManyToManyField(through='igog.OutgoingProduct', to='products.Product'),
        ),
    ]
