# Generated by Django 3.2 on 2021-05-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('igog', '0004_auto_20210509_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.supplier'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.buyer'),
        ),
        migrations.CreateModel(
            name='IncomingSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igog.incoming')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.supplier')),
            ],
        ),
    ]
