# Generated by Django 3.2 on 2021-05-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('igog', '0005_auto_20210510_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.buyer')),
                ('outgoing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igog.outgoing')),
            ],
        ),
    ]
