# Generated by Django 3.2 on 2021-05-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igog', '0006_outgoingbuyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingdeliverynote',
            old_name='incoming_id',
            new_name='incoming',
        ),
        migrations.RenameField(
            model_name='outgoingdeliverynote',
            old_name='outgoing_id',
            new_name='outgoing',
        ),
    ]
