# Generated by Django 3.2 on 2021-06-26 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('40dc6272-6e9a-454e-ab73-c1b13949bba6'), editable=False, unique=True, verbose_name='Public Identifier'),
        ),
    ]
