# Generated by Django 3.2 on 2021-06-27 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210626_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('07884850-26f3-4a7b-96b3-d5afa38fb362'), editable=False, unique=True, verbose_name='Public Identifier'),
        ),
    ]
