# Generated by Django 3.2 on 2021-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210627_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('admin', 'Admin'), ('input', 'input'), ('look', 'look')], default='look'),
        ),
    ]
