# Generated by Django 3.2 on 2021-06-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.baseentity')),
                ('num_ktp', models.PositiveBigIntegerField()),
                ('num_npwp', models.PositiveBigIntegerField()),
            ],
            bases=('entities.baseentity',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.baseentity')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
            bases=('entities.baseentity',),
        ),
    ]
