# Generated by Django 3.2 on 2021-08-26 11:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholders/products.jpg', storage=products.models.OverwriteStorage(), upload_to='products_images'),
        ),
    ]
