# Generated by Django 3.2 on 2021-05-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210509_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_default.jpg', upload_to='products_images'),
        ),
    ]
